# Generated by Django 3.2.9 on 2021-11-22 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20211121_0151'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('name', models.CharField(default='', max_length=20)),
                ('phone', models.IntegerField(default=0, max_length=10)),
                ('email', models.CharField(default='', max_length=30)),
                ('cid', models.AutoField(primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=500)),
            ],
        ),
    ]
