# Generated by Django 3.2.9 on 2021-11-22 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_contact_phone'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='Contact_table',
        ),
    ]
