# Generated by Django 3.2.9 on 2021-11-24 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_rename_contact_contact_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order_table',
            fields=[
                ('odrid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=39)),
                ('email', models.CharField(max_length=30)),
                ('state', models.IntegerField()),
                ('addr', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=20)),
                ('zipcode', models.CharField(max_length=15)),
            ],
        ),
    ]
