# Generated by Django 3.2.9 on 2021-11-24 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_order_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_table',
            name='state',
            field=models.CharField(max_length=20),
        ),
    ]
