# Generated by Django 3.2.9 on 2021-11-29 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_alter_order_table_state'),
    ]

    operations = [
        migrations.CreateModel(
            name='complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('com_name', models.CharField(max_length=20)),
                ('com_email', models.CharField(max_length=30)),
                ('com_sub', models.CharField(max_length=35)),
                ('com_msg', models.CharField(max_length=300)),
                ('com_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.order_table')),
            ],
        ),
    ]
