# Generated by Django 3.2.9 on 2021-11-29 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_rename_complaint_complaint_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint_table',
            name='com_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.order_table'),
        ),
    ]
