# Generated by Django 3.2.9 on 2021-11-29 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_alter_complaint_table_com_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint_table',
            name='com_id',
        ),
    ]
