# Generated by Django 3.2.9 on 2021-11-30 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_remove_complaint_table_com_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order_update',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderId', models.IntegerField(default='')),
                ('update_desc', models.CharField(max_length=1000)),
                ('upd_time', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
