# Generated by Django 3.2.9 on 2021-11-30 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_order_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_table',
            name='order_details',
            field=models.CharField(default='', max_length=2500),
        ),
    ]
