# Generated by Django 3.2.9 on 2021-11-30 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_order_table_order_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='cancel_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderid', models.IntegerField()),
                ('cancel_date', models.DateField()),
                ('email', models.CharField(max_length=30)),
            ],
        ),
    ]
